# Generated by Django 3.2.8 on 2022-01-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
